#!/usr/bin/env python3
"""Generate a per-species seasonal OCCURRENCE PRIOR for the ESP32 firmware.

Uses BirdNET's eBird-trained location+time meta-model to estimate, for each week
of the year at a FIXED location (default: Plainfield, IN), how likely each of our
74 target species is to occur. Emits a C header the firmware bakes into flash and
uses to softly weight detection scores by season -- exactly how BirdNET itself
narrows the candidate list by place + time of year.

The species ROW ORDER is taken from the model's own class_names
(best_model_model_config.json -> sorted Genus_species), so PRIOR[week][i] aligns
1:1 with model output index i (no remap needed on-device).

Run in the training container (the `birdnet` pip package provides the meta-model):
    pip install birdnet
    python make_occurrence_prior.py --config /out/best_model_model_config.json \
        --out /out/occurrence_prior.h --weeks 48

NOTE: BirdNET's meta-model is natively WEEKLY at 48 weeks (4 per month). Pass
--weeks 48 (default). The firmware maps day-of-year -> 0..weeks-1.
"""
from __future__ import annotations

import argparse
import json
import sys

import numpy as np

PLAINFIELD_LAT = 39.7042
PLAINFIELD_LON = -86.3994


def load_class_names(config_path: str) -> list[str]:
    """Model output order = class_names (sorted Genus_species) from the config."""
    d = json.load(open(config_path, encoding="utf-8"))
    cn = d.get("class_names")
    if not cn:
        raise SystemExit(f"no class_names in {config_path}")
    return [str(c) for c in cn]


def query_birdnet(lat: float, lon: float, weeks: int, classes: list[str]) -> np.ndarray:
    """Return a [weeks, len(classes)] occurrence table from BirdNET's GeoModel.

    BirdNET labels species as 'Scientific_Common'; our classes are 'Genus_species'
    (underscored). Map by the scientific (Genus species) prefix.
    """
    import birdnet

    model = birdnet.load("geo", "2.4", "tf")  # eBird location+week meta-model

    # our class 'Genus_species' -> index, keyed by lowercase 'genus species'
    sci_to_idx = {c.replace("_", " ").lower(): i for i, c in enumerate(classes)}
    n = len(classes)
    table = np.zeros((weeks, n), dtype=np.float32)

    for w in range(1, weeks + 1):
        r = model.predict(lat, lon, week=w, min_confidence=0.0)
        labels = list(r.species_list)     # 'Scientific_Common', parallel to probs
        probs = list(r.species_probs)
        for label, conf in zip(labels, probs):
            sci = str(label).split("_", 1)[0].strip().lower()
            j = sci_to_idx.get(sci)
            if j is not None:
                table[w - 1, j] = float(conf)
    return table


def emit_header(table: np.ndarray, classes: list[str], lat: float, lon: float,
                out_path: str) -> None:
    weeks, n = table.shape
    lines = []
    lines.append("/* AUTO-GENERATED by make_occurrence_prior.py -- do not edit by hand.")
    lines.append(f" * Seasonal eBird occurrence prior for lat={lat:.4f} lon={lon:.4f}")
    lines.append(f" * from BirdNET's location+time meta-model. {weeks} weeks x {n} species.")
    lines.append(" * PRIOR[week][i] aligns with model output index i (model class order). */")
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"#define BIRDNET_PRIOR_WEEKS   {weeks}")
    lines.append(f"#define BIRDNET_PRIOR_CLASSES {n}")
    lines.append("")
    lines.append("/* Occurrence likelihood in [0,1]; 0 = not expected that week. */")
    lines.append("static const float BIRDNET_OCCURRENCE_PRIOR"
                 f"[BIRDNET_PRIOR_WEEKS][BIRDNET_PRIOR_CLASSES] = {{")
    for w in range(weeks):
        vals = ", ".join(f"{table[w, i]:.3f}f" for i in range(n))
        lines.append(f"    {{ {vals} }},  /* week {w + 1} */")
    lines.append("};")
    lines.append("")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", default="/out/best_model_model_config.json")
    ap.add_argument("--lat", type=float, default=PLAINFIELD_LAT)
    ap.add_argument("--lon", type=float, default=PLAINFIELD_LON)
    ap.add_argument("--weeks", type=int, default=48, help="BirdNET native = 48")
    ap.add_argument("--out", default="/out/occurrence_prior.h")
    args = ap.parse_args()

    classes = load_class_names(args.config)
    print(f"{len(classes)} classes; querying BirdNET meta-model at "
          f"({args.lat:.4f}, {args.lon:.4f}) for {args.weeks} weeks ...", flush=True)
    table = query_birdnet(args.lat, args.lon, args.weeks, classes)

    ever = int((table.max(axis=0) > 0.0).sum())
    peak = table.max()
    print(f"species with any in-year occurrence: {ever}/{len(classes)}; peak={peak:.3f}",
          flush=True)
    # A few sanity prints: most/least seasonal species.
    span = table.max(axis=0) - table.min(axis=0)
    order = np.argsort(-span)
    print("most seasonal (max-min occurrence):")
    for j in order[:6]:
        print(f"  {classes[j]:28s} min={table[:,j].min():.3f} max={table[:,j].max():.3f}")

    emit_header(table, classes, args.lat, args.lon, args.out)
    print(f"wrote {args.out} ({args.weeks}x{len(classes)})", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
